apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment
    spec:
      containers:
      - image: virtualizacao
        imagePullPolicy: IfNotPresent
        name: virtualizacao
        resources: {}
        env:
        - name: NAME
          valueFrom: 
            configMapKeyRef:
              name: config
              key: name
status: {}
